global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: kafka-exporter
    static_configs:
      - targets:
          - kafka-exporter:9308

  - job_name: basecommerce
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:8081

  - job_name: searchservice
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:8082
